export const news = [
  {
    slug: 'rector-of-unsika-highlights-legal-and-ethical-aspects-of-artificial-intelligence',
    title: 'Higher Education at International Forum in China',
    date: '2025-05-23/24',
    desc: "This activity marks the continuation of UNSIKA's participation in the 2025 Belt and Road Academic Conference on Technical and Vocational Education and Training (TVET), held on May 23–24, 2025, in Shenzhen, China.",
    content: `RECTOR OF UNSIKA HIGHLIGHTS LEGAL AND ETHICAL ASPECTS OF ARTIFICIAL INTELLIGENCE IN HIGHER EDUCATION AT INTERNATIONAL FORUM IN CHINA.\n\nThe Rector of Universitas Singaperbangsa Karawang (UNSIKA), Prof. Dr. Ade Maman Suherman, S.H., M.Sc., was invited as a keynote speaker at the 2025 Belt and Road Academic Conference on Technical and Vocational Education and Training (TVET) held in Shenzhen, China, on May 23–24, 2025.\n\nIn his presentation, Prof. Ade Maman Suherman emphasized the importance of legal and ethical aspects in the development and application of Artificial Intelligence (AI) in higher education. He highlighted that while AI offers significant opportunities to improve the quality and accessibility of education, it also presents challenges related to data privacy, academic integrity, and the potential for bias in automated decision-making.\n\n"Universities must play an active role in ensuring that the use of AI in education is guided by strong ethical principles and legal frameworks," said Prof. Ade. He also encouraged international collaboration to develop global standards and best practices for AI in education.\n\nThe conference was attended by representatives from more than 20 countries, including academics, policymakers, and industry leaders. The event provided a platform for sharing experiences and strategies to enhance the quality and relevance of technical and vocational education in the era of digital transformation.\n\nUNSIKA's participation in this international forum reflects its commitment to global engagement and its proactive role in addressing emerging issues in higher education.`
  },
  { slug: 'international-summer-course-2024', title: 'International Summer Course 2024', date: '2024-07-15', desc: 'Join our upcoming summer course with international lecturers and students.', content: 'Full details about the International Summer Course 2024. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque euismod, urna eu tincidunt consectetur, nisi nisl aliquam nunc, eget aliquam massa nisl quis neque.' },
  { slug: 'scholarship-applications-open', title: 'Scholarship Applications Open', date: '2024-08-01', desc: 'Apply now for scholarships for the 2024/2025 academic year.', content: 'Full details about scholarship applications. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque euismod, urna eu tincidunt consectetur, nisi nisl aliquam nunc, eget aliquam massa nisl quis neque.' },
  { slug: 'new-partnership-with-seoul-university', title: 'New Partnership with Seoul University', date: '2024-07-20', desc: 'UNSIKA IRO establishes a new partnership for joint research and student exchange.', content: 'Full details about the new partnership with Seoul University. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque euismod, urna eu tincidunt consectetur, nisi nisl aliquam nunc, eget aliquam massa nisl quis neque.' },
]; 